### ISSUE TITLE
Links to examples give 404

### ISSUE THREAD

**Issue by codecleric** [herby/trapped#8]
Both http://www.herby.sk/trapped/example-counter/counter.html and  http://www.herby.sk/trapped/example-todo/todo.html are returning 404 from Nginx

**Comment by herby** [comment]
Both examples are reinstalled, Counter example works, ToDo example needs some work to migrate to existing structure as there were changes from 0.3.x to 0.4.x.

**Comment by codecleric** [comment]
Thank you sir!
